### ISSUE TITLE
Demetricate other services

### ISSUE THREAD

**Issue by palmerabollo** [brian-yu/hn-demetricator#1]
Very good idea, Brian. Are you open to contributions to "demetricate" other services (Twitter, Instagram, Facebook, etc)?

**Comment by brian-yu** [comment]
Hey Guido, yes, that would be awesome!

In the interest of not duplicating work, though, there are a couple of extensions out there that already demetricate [Twitter](https://bengrosser.com/projects/twitter-demetricator/), [Instagram](https://bengrosser.com/projects/instagram-demetricator/), and [Facebook](https://bengrosser.com/projects/facebook-demetricator/). There's also this other project, [Disengaged](https://github.com/a13o/disengaged), that might be of interest.

It does seem like it would be *quite* useful to bundle all of these extensions into just one 'Demetricator' extension!
