### ISSUE TITLE
Posts with 0 upvotes stand out

### ISSUE THREAD

**Issue by dchege711** [brian-yu/hn-demetricator#2]
Repro: With HN enhancement suite, browse HN and hope for a post that has zero comments:

<img width="1337" alt="Screen Shot 2020-07-12 at 3 20 51 PM" src="https://user-images.githubusercontent.com/13133947/87257841-5f64e980-c453-11ea-96c9-d5d07c78eed0.png">

According to

https://github.com/brian-yu/hn-demetricator/blob/b765df294d0f5e1679970bd37f15c3cc0ab0cdad/hacker_news.js#L22-L31

it's by design. Why is this so?

IMO, a post that shows 0 draws more attention to itself, which defeats the purpose of demetricating HN...

**Comment by brian-yu** [comment]
You're right in that posts with 0 comments draw attention to themselves. I agree that it'd be better to hide that as well.

If you want, you could submit a PR to fix that. Otherwise, I can do it too. Thanks for making the issue!

**Comment by dchege711** [comment]
I made this PR using Github's online editor. I don't think it'll break anything, but I haven't tested it. Your call 😄
